### ISSUE TITLE
Hoverfy middleware not work with only binary

### ISSUE THREAD

**Issue by norguhtar** [SpectoLabs/hoverfly#1007]
## Description of the bug

When i'm run hoverfly with middleware binary. Middleware broken

## Steps to reproduce the issue

Create binary middleware. Then run like
```
hoverfly -webserver -import simulation.json -middleware mymiddleware 
```

### Observed result
**Hoverfly error messages seen (If none, say none)**
```
2022/02/14 15:14:44 http: panic serving 127.0.0.1:39850: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc00033ebe0)
        /usr/local/go/src/net/http/server.go:1804 +0x153
panic(0xbc1ee0, 0x1207e60)
        /usr/local/go/src/runtime/panic.go:971 +0x499
os.(*File).Name(...)
        /usr/local/go/src/os/file.go:55
github.com/SpectoLabs/hoverfly/core/middleware.Middleware.executeMiddlewareLocally(0x7ffe2a374210, 0x2f, 0x0, 0x0, 0x0, 0x190, 0xc000169560, 0x112, 0x0, 0x0, ...)
        /home/circleci/hoverfly/core/middleware/local_middleware.go:14 +0xdb
github.com/SpectoLabs/hoverfly/core/middleware.(*Middleware).Execute(0xc00016a650, 0x190, 0xc000169560, 0x112, 0x0, 0x0, 0xc0002e98f0, 0x0, 0x0, 0x0, ...)
        /home/circleci/hoverfly/core/middleware/middleware.go:115 +0x178
github.com/SpectoLabs/hoverfly/core.Hoverfly.ApplyMiddleware(0x0, 0xdb44d8, 0xc00000e770, 0xdb5ba0, 0xc00004ba00, 0xc0002e8e10, 0xc00016a600, 0xc00004b8e0, 0xc000173050, 0xc000319440, ...)
        /home/circleci/hoverfly/core/hoverfly_funcs.go:366 +0x11f
github.com/SpectoLabs/hoverfly/core/modes.SimulateMode.Process(0xdac248, 0xc0002cfea0, 0xc829f5, 0x9, 0xc000232300, 0xc0000ee004, 0x2a, 0xc0000ee000, 0x3, 0xc0000a2950, ...)
        /home/circleci/hoverfly/core/modes/simulate_mode.go:52 +0x19a
```

### Expected result

Run with binary middleware. When i'm run middleware with this options
```
hoverfly -webserver -import simulation.json -middleware "middleware "
```
hoverfly worked as expected

## Additional relevant information
1. Hoverfly version:  v1.3.3

**Comment by tommysitu** [comment]
it's probably because you are not specifying a script for it to run? 
```
  -middleware string
    	Set middleware by passing the name of the binary and the path of the middleware script separated by space. (i.e. '-middleware "python script.py"')
```

is `mymiddleware` some sort of self-contained / stand-alone program you can run in the terminal? Might need to make some adjustment to allow hoverfly to run it in such scenario

**Comment by norguhtar** [comment]
> is mymiddleware some sort of self-contained / stand-alone program you can run in the terminal? Might need to make some adjustment to allow hoverfly to run it in such scenario

Yes is it. 

Also hoverctl already support this scenario via two separate flags

```
Usage:
  hoverctl middleware [flags]

Flags:
      --binary string   An absolute or relative path to a binary that Hoverfly will execute as middleware
      --remote string   A URL to a remote address that will be called by Hoverfly as middleware
      --script string   An absolute or relative path to a script that will be executed by the middleware binary
```

It worked.

**Comment by tommysitu** [comment]
fixed: https://github.com/SpectoLabs/hoverfly/releases/tag/v1.3.4
