### ISSUE TITLE
hoverctl export doesn't fail gracefully

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly#411]
With hoverctl v10.1

When I run `hoverctl export` without an argument, I am getting this error: 
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x415dc0, 0xc4200120f0)
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
github.com/SpectoLabs/hoverfly/hoverctl/cmd.glob..func4(0x6a3860, 0x6c7608, 0x0, 0x0)
	/private/tmp/hoverfly-20170217-87583-fvhy7v/hoverfly-0.10.1/gopath/src/github.com/SpectoLabs/hoverfly/hoverctl/cmd/export.go:21 +0x1b8
github.com/SpectoLabs/hoverfly/vendor/github.com/spf13/cobra.(*Command).execute(0x6a3860, 0x6c7608, 0x0, 0x0, 0x6a3860, 0x6c7608)
	/private/tmp/hoverfly-20170217-87583-fvhy7v/hoverfly-0.10.1/gopath/src/github.com/SpectoLabs/hoverfly/vendor/github.com/spf13/cobra/command.go:565 +0x411
github.com/SpectoLabs/hoverfly/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x6a4260, 0x0, 0xc42004ff38, 0x5f7b)
	/private/tmp/hoverfly-20170217-87583-fvhy7v/hoverfly-0.10.1/gopath/src/github.com/SpectoLabs/hoverfly/vendor/github.com/spf13/cobra/command.go:651 +0x367
github.com/SpectoLabs/hoverfly/vendor/github.com/spf13/cobra.(*Command).Execute(0x6a4260, 0x6a4260, 0x485eef)
	/private/tmp/hoverfly-20170217-87583-fvhy7v/hoverfly-0.10.1/gopath/src/github.com/SpectoLabs/hoverfly/vendor/github.com/spf13/cobra/command.go:610 +0x2b
github.com/SpectoLabs/hoverfly/hoverctl/cmd.Execute(0x4c47f0, 0x7)
	/private/tmp/hoverfly-20170217-87583-fvhy7v/hoverfly-0.10.1/gopath/src/github.com/SpectoLabs/hoverfly/hoverctl/cmd/root.go:30 +0x57
main.main()
	/private/tmp/hoverfly-20170217-87583-fvhy7v/hoverfly-0.10.1/gopath/src/github.com/SpectoLabs/hoverfly/hoverctl/main.go:10 +0x39
```

I think it should fail gracefully witha warning message saying "Missing argument for exporting file" or similar.

**Comment by benjih** [comment]
Hey @tommysitu,

This has recently come about due to switching to [spf13/cobra](http://github.com/spf13/cobra) in hoverctl. How does something like this look to you?

```
benjih@Benjis-MBP-2 ~/s/g/s/g/S/hoverfly (hoverctl-export)> target/hoverctl export
You have not provided a path to simulation

Try hoverctl export --help for more information
```

**Comment by tommysitu** [comment]
Looks perfect @benjih

**Comment by benjih** [comment]
This is currently on master and awaiting deployment.

**Comment by benjih** [comment]
Hey @tommysitu, we've release v0.10.2 which now includes the fix to this issue.
