### ISSUE TITLE
Matcher name should be case-insensitive

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly#836]
## Description of the bug
Hoverfly is panic and stopped when trying to match a request with a simulation that contains unknown matcher name or matcher name with incorrect capitalization. 

## Steps to reproduce the issue

1. create a simulation by capturing. Change an exact matcher from
```
{
   "matcher": "exact",
   "value": "/"
 }
```
```
{
   "matcher": "Exact",
   "value": "/"
 }
```
2. Re-import the simulation
3. Make the same request again with Hoverfly as a proxy. 

### Observed result
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1496c55]

goroutine 66 [running]:
github.com/SpectoLabs/hoverfly/core/matching.FieldMatcher(0xc00033f880, 0x1, 0x1, 0xc00003a8f1, 0x1, 0xc0000c89b0)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/core/matching/field_matcher.go:17 +0xf5
github.com/SpectoLabs/hoverfly/core/matching.MatchingStrategyRunner(0xc00003a8f1, 0x1, 0xc0000c88f0, 0x3, 0xc0000d05c0, 0x15, 0xc00003a8d0, 0x5, 0xc00020d0b0, 0x0, ...)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/core/matching/matching_strategy_runner.go:26 +0x1e8
github.com/SpectoLabs/hoverfly/core/matching.Match(0x17fe7e1, 0x9, 0xc00003a8f1, 0x1, 0xc0000c88f0, 0x3, 0xc0000d05c0, 0x15, 0xc00003a8d0, 0x5, ...)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/core/matching/matcher.go:12 +0x183
github.com/SpectoLabs/hoverfly/core.(*Hoverfly).GetResponse(0xc0002259a0, 0xc00003a8f1, 0x1, 0xc0000c88f0, 0x3, 0xc0000d05c0, 0x15, 0xc00003a8d0, 0x5, 0xc00020d0b0, ...)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/core/hoverfly_funcs.go:65 +0x430
github.com/SpectoLabs/hoverfly/core/modes.SimulateMode.Process(0x19b62e0, 0xc0002259a0, 0x17fe7e1, 0x9, 0xc000190100, 0xc00003a8f1, 0x1, 0xc0000c88f0, 0x3, 0xc0000d05c0, ...)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/core/modes/simulate_mode.go:44 +0xbd
github.com/SpectoLabs/hoverfly/core.(*Hoverfly).processRequest(0xc0002259a0, 0xc000190100, 0x1f79480)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/core/hoverfly.go:191 +0x15b
github.com/SpectoLabs/hoverfly/core.NewProxy.func4(0xc000190100, 0xc0000dc370, 0xc0000dc370, 0x1)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/core/proxy.go:67 +0x6a
github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy.FuncReqHandler.Handle(0xc00021f2d0, 0xc000190100, 0xc0000dc370, 0xc00003a801, 0xc000160080)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy/actions.go:19 +0x3a
github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy.(*ReqProxyConds).Do.func1(0xc000190100, 0xc0000dc370, 0x0, 0x0)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy/dispatcher.go:200 +0xcc
github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy.FuncReqHandler.Handle(0xc000292520, 0xc000190100, 0xc0000dc370, 0xc00037dd68, 0x3)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy/actions.go:19 +0x3a
github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy.(*ProxyHttpServer).filterRequest(0xc000236120, 0xc000190100, 0xc0000dc370, 0x0, 0x0)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy/proxy.go:59 +0x74
github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy.(*ProxyHttpServer).handleHttps.func2(0x19bdee0, 0xc0000d2c18, 0xc0000a9500, 0xc000295a90, 0xc000190700, 0xc000236120)
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy/https.go:220 +0x534
created by github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy.(*ProxyHttpServer).handleHttps
	/private/tmp/hoverfly-20190215-4108-1ygmiix/hoverfly-1.0.0-rc.2/gopath/src/github.com/SpectoLabs/hoverfly/vendor/github.com/SpectoLabs/goproxy/https.go:190 +0x4f3
```

### Expected result
The matcher name should be case-insensitive. If the matcher name is unknown, Hoverfly will skip the matcher, and print a warning. It should not panic and exist.  

## Additional relevant information
Hoverfly version: v1.0.0-rc.2

**Comment by tommysitu** [comment]
Fixed in v1.0.0
